import { StyleSheet } from "react-native"


export const styles = StyleSheet.create({
    description: {
        marginLeft: 24,
        marginRight: 24,
        gap: 19,
    },
    cardContainer: {
        display: 'flex',
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
    },
    card: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 12,
    },
    step: {
        display: 'flex',
        width: 32,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 0,
        paddingTop: 5,
        paddingBottom: 7,
        borderRadius: 64,
        margin: 0,
        backgroundColor: '#F5F5F5',
        fontSize: 14,
        fontWeight: 600,

    },
    stepItem: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: 4,
        flexWrap: 'wrap',
        flexShrink: 1,
    },
    stepTitle: {
        display: 'flex',
        fontSize: 14,
        fontWeight: 600,
        flexDirection: 'column',
        alignItems: 'flex-start',
        alignSelf: 'stretch',
        gap: 4,
    },
    cardTracking: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        gap: 4,
        alignSelf: 'stretch',
    },
    footer: {
        position: 'fixed',
        bottom: 24,
        display: 'flex',
        alignSelf: 'center',
    },
    containerTracking: {
        display: 'flex',
        padding: 16,
        flexDirection: 'column',
        alignItems: 'flex-start',
        borderRadius: 8,
        backgroundColor: '#F5F5F5',
        alignSelf: 'center',
    },
    containerBody: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'flex-start',
        alignSelf: 'stretch',
        gap: 4,
    },
    titleContainer: {
        display: 'flex',
        alignItems: 'center',
        alignSelf: 'stretch',
        flexDirection: 'row',
        gap: 6,
    },
    trackingButton: {
        display: 'flex',
        paddingVertical: 12,
        paddingHorizontal: 24,
        justifyContent: 'center',
        alignItems: 'center',
        gap: 8,
        marginTop: 16,
        width: '100%',
        alignSelf: 'center',
        borderRadius: 64,
        backgroundColor:  '#EB0A1E',
    },
    callCenterButton: {
        display: 'flex',
        paddingVertical: 12,
        paddingHorizontal: 24,
        justifyContent: 'center',
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        borderRadius: 64,
        backgroundColor:'#F5F5F5',
        width: '100%',
        marginTop: 24,
    }
})