import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  label: {
    textAlign: 'right',
    flexShrink: 1,
  },
  bodyContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingTop: 8,
    paddingRight: 24,
    paddingBottom: 24,
    paddingLeft: 24,
    alignItems: 'flex-start',
    gap: 24,
  },
  reasonContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 16,
    alignSelf: 'stretch',
  },
  container: {
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 8,
  },
  rowButton: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  radio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#242424",
    justifyContent: "center",
    alignItems: "center",
  },
  radioCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#EB0A1E",
    justifyContent: "center",
    alignItems: "center",
  },
  radioSelected: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#EB0A1E",
  },
  labelButton: {
    marginLeft: 10,
    fontSize: 16,
  },
  footer: {
    width: '100%',
    position: 'fixed',
    bottom: 24,
    alignSelf: 'center',
    paddingLeft: 24,
    paddingRight: 24,
  },
  NextButton: {
    display: 'flex',
    paddingVertical: 12,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    marginTop: 16,
    width: '100%',
    alignSelf: 'center',
    borderRadius: 64,
    backgroundColor: '#EB0A1E',
  },
  callCenterButton: {
    display: 'flex',
    paddingVertical: 12,
    paddingHorizontal: 24,
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 64,
    backgroundColor: '#F5F5F5',
    marginTop: 24,
  }
})